name: Sync TOR Exit Nodes
on:
  schedule:
    - cron: '30 18 * * *' # Runs every day at 12:00 AM IST (18:30 UTC)
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch and Clean TOR List
        run: |
          curl -s https://check.torproject.org/exit-addresses | grep "ExitAddress" | awk '{print $2}' | sort -u > tor_ips.txt

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add tor_ips.txt
          git commit -m "Update TOR exit nodes" || exit 0
          git push
